spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: bp_db_schema
  datasource:
    # platform: postgres
    url: jdbc:postgresql://localhost:5432/bp_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
